videobridge {
    http-servers {
        public {
            port = __PORT_JVB_PUB__
        }
        private {
            port = __PORT_JVB_PRIV__
        }
    }
    websockets {
        enabled = true
        domain = "__DOMAIN__:443"
        tls = true
    }
}
