videobridge {
    http-servers {
        public {
            port = __PORT_JVB__
        }
        private {
            port = -1
        }
    }
    websockets {
        enabled = true
        domain = "__DOMAIN__:443"
        tls = true
    }
}
